// This file is automatically generated by i18next-cli. Do not edit manually.
export default interface Resources {
  "app": {
    "errors": {
      "import": "Erreur lors de l'import : {{detail}}",
      "open": "Erreur à l'ouverture : {{detail}}"
    },
    "replace": {
      "closeActForShow": "Un numéro est ouvert. Le fermer pour ouvrir le spectacle importé ?",
      "replaceAct": "Un numéro est déjà ouvert. Le remplacer par celui importé ?",
      "replaceShow": "Un spectacle est déjà ouvert. Le remplacer par celui importé ?",
      "title": "Remplacer ?"
    }
  },
  "audio": {
    "addPause": "Ajouter une pause",
    "addStep": "Ajouter une étape",
    "categoryMusic": "Musique",
    "categoryPause": "Pause",
    "download": {
      "downloadingTitle": "Téléchargement de « {{title}} »…",
      "downloadingTitlePercent": "Téléchargement de « {{title}} » : {{percent}} %",
      "fetchingInfo": "Récupération des informations de la vidéo…",
      "inProgress": "Téléchargement en cours…",
      "initializing": "Initialisation…",
      "submit": "Télécharger",
      "urlLabel": "URL du fichier audio",
      "urlPlaceholder": "https://exemple.com/musique.mp3",
      "youtubeHint": "Télécharge l'audio depuis YouTube (inclus dans l'application)",
      "youtubeLabel": "Lien de la vidéo YouTube",
      "youtubePlaceholder": "https://www.youtube.com/watch?v=..."
    },
    "errors": {
      "add": "Erreur lors de l'ajout audio : {{detail}}"
    },
    "fromUrl": "Depuis une URL",
    "item": {
      "clickToRename": "Cliquer pour renommer",
      "cue": "Top de départ",
      "cuePlaceholder": "Top de départ…",
      "duration": "Durée",
      "loop": "Répétée jusqu'à Suivant",
      "missing": "Fichier introuvable",
      "missingFile": "Fichier introuvable : {{filename}}",
      "moveTo": "Déplacer vers une autre partie",
      "play": "Lire",
      "volume": "Volume : {{percent}} %"
    },
    "pause": {
      "autoAdvance": "Durée avant enchaînement automatique",
      "durationField": "Durée en secondes (vide = attente manuelle)",
      "label": "Pause",
      "seekHere": "Se positionner sur cette étape"
    },
    "player": {
      "dismissResume": "Ignorer",
      "fadeIn": "Fade in",
      "fadeOut": "Fade out",
      "next": "Piste suivante",
      "outputFailed": "Sortie audio choisie indisponible ({{detail}}) : le son part sur la sortie par défaut du système.",
      "pause": "Pause",
      "pauseRemaining": "Pause — <strong>{{seconds}} s</strong> restantes",
      "play": "Lecture",
      "playbackError": "Lecture impossible : le fichier est introuvable ou dans un format non pris en charge.",
      "previous": "Précédent (ou retour au début de la piste)",
      "resume": "Reprendre",
      "resumeOffer": "La lecture s'est interrompue sur « {{track}} » à {{time}}.",
      "stop": "Stop",
      "stopArmed": "Appuyez de nouveau sur Stop pour arrêter",
      "waiting": "En attente — appuyez sur Play pour continuer"
    },
    "settings": {
      "endBeforeStart": "L'heure de fin doit être supérieure à l'heure de début",
      "endBeyondFile": "La fin dépasse la durée du fichier ({{duration}})",
      "endLabel": "Fin (optionnel)",
      "endPlaceholder": "ex : 2:45 ou 165",
      "fadeInLabel": "Fade in — durée en secondes",
      "fadeOutLabel": "Fade out — durée en secondes",
      "fadesTooLong": "Le fade in et le fade out cumulés dépassent la durée jouée ({{length}})",
      "invalidEnd": "Heure de fin invalide (format : m:ss.d ou secondes)",
      "invalidFadeIn": "Durée de fade in invalide (en secondes, ex : 3)",
      "invalidFadeOut": "Durée de fade out invalide (en secondes, ex : 3)",
      "invalidStart": "Heure de début invalide (format : m:ss.d ou secondes)",
      "loop": "Répéter jusqu'à Suivant",
      "loopHint": "L'extrait reprend à son début à chaque fin, et Suivant enchaîne avec le fondu de sortie habituel. Utile pour une musique d'attente de durée inconnue.",
      "playPreview": "Lire l'aperçu",
      "secondsPlaceholder": "ex : 3",
      "startBeyondFile": "Le début dépasse la durée du fichier ({{duration}})",
      "startLabel": "Début (optionnel)",
      "startPlaceholder": "ex : 0:30.5 ou 30",
      "title": "Paramètres — {{name}}",
      "waveformError": "Impossible de charger la forme d'onde."
    },
    "thisComputer": "Cet ordinateur",
    "youtube": "YouTube"
  },
  "common": {
    "actions": {
      "back": "Retour",
      "browse": "Parcourir",
      "cancel": "Annuler",
      "close": "Fermer",
      "continue": "Continuer",
      "create": "Créer",
      "creating": "Création...",
      "delete": "Supprimer",
      "rename": "Renommer",
      "save": "Enregistrer"
    },
    "duration": {
      "hours": "{{h}} h",
      "hoursMinutes": "{{h}} h {{m}}",
      "minutes": "{{m}} min"
    },
    "settings": "Paramètres",
    "trackInAct": "« {{track}} » ({{act}})"
  },
  "editor": {
    "addPart": "Ajouter une partie",
    "battery": {
      "charging": "En charge",
      "noEstimate": "Sur batterie — autonomie non estimée par le système",
      "remaining": "Autonomie restante : {{time}}"
    },
    "checkShow": "Vérifier le spectacle",
    "confirm": {
      "cleanupMessage_one": "{{count}} fichier audio que plus aucun élément n'utilise sera supprimé du dossier. Cette action est définitive.",
      "cleanupMessage_other": "{{count}} fichiers audio que plus aucun élément n'utilise seront supprimés du dossier. Cette action est définitive.",
      "closeMessage": "La musique va s'arrêter et le mode spectacle sera désactivé.",
      "closeTitle": "Fermer le spectacle ?",
      "quit": "Quitter",
      "quitMessage": "Une piste est en cours ou le mode spectacle est actif. Quitter arrêtera la musique.",
      "quitTitle": "Quitter Régie Son ?",
      "showModeOff": "Désactiver",
      "showModeOffMessage": "Les notifications reviendront et la mise en veille ne sera plus bloquée.",
      "showModeOffTitle": "Désactiver le mode spectacle ?"
    },
    "defaultName": {
      "act": "Numéro {{index}}",
      "hostSegment": "Présentation {{index}}",
      "intermission": "Entracte {{index}}"
    },
    "editMode": {
      "label": "Édition",
      "lockedByShow": "Édition verrouillée pendant le mode spectacle",
      "off": "Mode édition inactif",
      "on": "Mode édition actif"
    },
    "emptyState": "Aucun élément — commencez par ajouter un numéro, un entracte ou une présentation.",
    "errors": {
      "cleanup": "Erreur lors du nettoyage : {{detail}}",
      "export": "Erreur lors de l'export : {{detail}}",
      "import": "Erreur lors de l'import : {{detail}}"
    },
    "exportAct": "Exporter le numéro",
    "exportShow": "Exporter le projet",
    "retrySave": "Réessayer",
    "runningTime": {
      "remaining": "Reste {{duration}}",
      "remainingAtLeast": "Reste au moins {{duration}}",
      "title": "Durée de lecture, sans les enchaînements entre les parties ni les pauses sans durée",
      "total": "Durée : {{duration}}",
      "totalAtLeast": "Durée : au moins {{duration}}"
    },
    "saveFailed": "Modifications non enregistrées : {{detail}}",
    "saved": "✓ Sauvegardé",
    "showMode": {
      "activate": "Activer le mode spectacle",
      "active": "Mode spectacle actif",
      "activeTitle": "Mode spectacle actif : notifications coupées, veille bloquée — cliquer pour désactiver",
      "inactive": "Mode spectacle",
      "inactiveTitle": "Activer le mode spectacle : couper les notifications et bloquer la mise en veille"
    },
    "showView": {
      "close": "Quitter la vue spectacle",
      "endOfShow": "Fin du spectacle",
      "idle": "Rien n'est en cours",
      "now": "En cours",
      "offer": "Mode spectacle activé. Passer en vue spectacle ?",
      "open": "Vue spectacle",
      "openTitle": "Ouvrir la vue spectacle : plein écran, gros caractères, sans édition",
      "title": "Vue spectacle",
      "upNext": "À suivre"
    },
    "undo": {
      "partDeleted": "« {{name}} » supprimé",
      "redoTitle": "Rétablir la modification annulée (Ctrl+Y)",
      "stepDeleted": "Étape supprimée",
      "stepMoved": "Étape déplacée vers « {{name}} »",
      "undo": "Annuler",
      "undoTitle": "Annuler la dernière modification (Ctrl+Z)"
    },
    "verify": {
      "cleanup": "Nettoyer",
      "cleanupTitle": "Supprimer les fichiers orphelins",
      "dismiss": "Masquer",
      "missingFiles_one": "{{count}} fichier manquant",
      "missingFiles_other": "{{count}} fichiers manquants",
      "orphanFiles_one": "{{count}} fichier orphelin dans le dossier",
      "orphanFiles_other": "{{count}} fichiers orphelins dans le dossier"
    }
  },
  "errors": {
    "archive": {
      "corrupt": "Archive corrompue : {{name}} illisible.",
      "createEntryFailed": "Création : {{detail}}",
      "createFailed": "Impossible de créer l'archive : {{detail}}",
      "createNamedFailed": "Création {{name}} : {{detail}}",
      "entryTooLarge": "Archive refusée : {{name}} dépasse {{limit}} Mo une fois décompressé.",
      "extractFailed": "Extraction : {{detail}}",
      "extractNamedFailed": "Extraction {{name}} : {{detail}}",
      "fileMissingInArchive": "Fichier manquant dans l'archive : {{name}}",
      "finishFailed": "Finalisation de l'archive : {{detail}}",
      "invalid": "Archive invalide : {{detail}}",
      "missingFile": "Fichier {{name}} introuvable",
      "missingNumeroJson": "Archive invalide : numero.json manquant",
      "noAct": "Archive invalide : aucun numéro",
      "openFailed": "Ouverture de l'archive : {{detail}}",
      "readDirFailed": "Lecture dossier : {{detail}}",
      "readEntryFailed": "Lecture entrée : {{detail}}",
      "readNamedFailed": "Lecture {{name}} : {{detail}}",
      "targetProjectInvalid": "Projet cible invalide : {{detail}}",
      "tooLarge": "Archive refusée : son contenu dépasse {{limit}} Mo une fois décompressé.",
      "unsafePath": "Chemin invalide dans l'archive : {{name}}",
      "zipFailed": "Zip : {{detail}}"
    },
    "battery": {
      "accessFailed": "Accès à la batterie : {{detail}}",
      "enumerateFailed": "Énumération des batteries : {{detail}}",
      "readFailed": "Lecture de la batterie : {{detail}}"
    },
    "cloud": {
      "codeNotFound": "Code introuvable ou fichier expiré.",
      "connectionFailed": "Erreur de connexion : {{detail}}",
      "fileTooLarge": "Fichier trop volumineux ({{size}} Mo). Limite du service : {{limit}} Mo.",
      "httpClientFailed": "Erreur client HTTP : {{detail}}",
      "invalidCode": "Code invalide.",
      "notAShow": "Ce code ne correspond pas à un spectacle Régie Son.",
      "notAnAct": "Ce code ne correspond pas à un numéro Régie Son.",
      "notAnArchive": "Le fichier reçu n'est pas une archive valide.",
      "readDownloadedFailed": "Lecture du fichier téléchargé : {{detail}}",
      "readMetadataFailed": "Lecture métadonnées : {{detail}}",
      "remoteFileTooLarge": "Fichier distant trop volumineux ({{size}} Mo).",
      "serviceHttpError": "Erreur du service cloud (HTTP {{status}})",
      "sharedActNotShow": "Ce code partage un numéro Régie Son et non un spectacle. Utilisez l'option « Importer un numéro » à la place.",
      "sharedShowNotAct": "Ce code partage un spectacle Régie Son et non un numéro. Utilisez l'option « Importer un spectacle » à la place.",
      "unexpectedResponse": "Réponse inattendue du service : {{detail}}",
      "unexpectedUrl": "URL inattendue : {{detail}}"
    },
    "download": {
      "cancelled": "Téléchargement annulé.",
      "checksumMismatch": "Le yt-dlp téléchargé ne correspond pas à sa somme de contrôle : mise à jour abandonnée.",
      "checksumMissing": "La somme de contrôle de yt-dlp est absente de la publication : mise à jour abandonnée.",
      "chmodFailed": "chmod : {{detail}}",
      "createFileFailed": "Impossible de créer le fichier : {{detail}}",
      "createPathFailed": "Impossible de créer {{path}} : {{detail}}",
      "dataDirUnknown": "Impossible de déterminer le dossier de données : {{detail}}",
      "failed": "Erreur de téléchargement : {{detail}}",
      "fileNotFoundAfter": "Fichier introuvable après téléchargement",
      "fileTooLarge": "Fichier trop volumineux ({{size}} Mo). Limite : {{limit}} Mo.",
      "fileTooLargeLimit": "Fichier trop volumineux (limite : {{limit}} Mo).",
      "httpStatus": "Erreur HTTP {{status}} : {{url}}",
      "httpStatusUpdate": "Erreur HTTP {{status}} lors du téléchargement",
      "invalidUrl": "Lien invalide : collez une adresse qui commence par http:// ou https://.",
      "metadataFailed": "metadata : {{detail}}",
      "notAudio": "Ce lien ne mène pas à un fichier audio (le serveur a renvoyé une page ou un autre type de fichier). Utilisez un lien de téléchargement direct.",
      "notExecutable": "Le binaire téléchargé n'est pas exécutable sur ce système.",
      "releaseInfoInvalid": "Impossible de lire la dernière version de yt-dlp : {{detail}}",
      "replaceBinaryFailed": "Impossible de remplacer l'ancien binaire : {{detail}}",
      "unexpected": "Erreur : {{detail}}",
      "ytDlpBroken": "yt-dlp ne démarre pas correctement.",
      "ytDlpFailed": "Erreur yt-dlp : {{detail}}",
      "ytDlpMissing": "yt-dlp est introuvable dans cette installation.",
      "ytDlpNotFound": "yt-dlp introuvable : {{detail}}"
    },
    "friendly": {
      "ageRestricted": "Cette vidéo est soumise à une restriction d'âge.",
      "connectionRefused": "Impossible de se connecter au serveur.",
      "dnsFailed": "Impossible de résoudre l'adresse du serveur.",
      "http401": "Authentification requise (401).",
      "http403": "Accès refusé par le serveur (403).",
      "http404": "URL introuvable (404).",
      "http5xx": "Erreur côté serveur, réessayez plus tard.",
      "invalidResponse": "Réponse serveur invalide.",
      "membersOnly": "Cette vidéo est réservée aux membres.",
      "noCompatibleAudio": "Aucune piste audio compatible trouvée.",
      "privateVideo": "Cette vidéo est privée et ne peut pas être téléchargée.",
      "timeout": "Délai d'attente dépassé. Vérifiez votre connexion.",
      "tlsError": "Erreur de sécurité TLS avec le serveur.",
      "unsupportedUrl": "Ce lien n'est pas pris en charge.",
      "videoUnavailable": "Cette vidéo n'est plus disponible."
    },
    "io": {
      "copyFailed": "Impossible de copier le fichier : {{detail}}",
      "createDirFailed": "Impossible de créer le dossier : {{detail}}",
      "deleteFailed": "Impossible de supprimer : {{detail}}",
      "fileTooLarge": "Fichier trop volumineux pour être lu ({{size}} Mo). Limite : {{limit}} Mo.",
      "invalidFilename": "Nom de fichier invalide",
      "pathNotAllowed": "Accès refusé : ce fichier n'appartient pas à un spectacle ou un numéro ouvert.",
      "readFailed": "Erreur de lecture : {{detail}}",
      "readFileFailed": "Impossible de lire le fichier : {{detail}}",
      "readProjectFailed": "Impossible de lire le projet : {{detail}}",
      "saveFailed": "Impossible de sauvegarder : {{detail}}",
      "serializeFailed": "Erreur de sérialisation : {{detail}}",
      "writeFailed": "Erreur d'écriture : {{detail}}"
    },
    "project": {
      "alreadyExists": "Le dossier {{path}} contient déjà un spectacle ou un numéro. Choisissez-en un autre.",
      "invalidFile": "Fichier projet invalide : {{detail}}",
      "invalidItems": "Items invalides pour « {{name}} » : {{detail}}"
    },
    "raw": "Erreur : {{detail}}",
    "showMode": {
      "appleScriptFailed": "Erreur : {{detail}}",
      "audioApiFailed": "{{api}} : {{detail}}",
      "desktopUnsupported": "Couper les notifications n'est possible que sous GNOME (bureau détecté : {{desktop}}). Activez manuellement le mode Ne pas déranger.",
      "gnomeFailed": "Impossible de modifier les notifications GNOME. Activez manuellement le mode Ne pas déranger.",
      "gsettingsMissing": "gsettings non disponible. Activez manuellement le mode Ne pas déranger.",
      "macosManual": "Activez manuellement le mode Ne pas déranger dans Réglages Système > Notifications.",
      "systemSoundsNotFound": "Session SystemSounds introuvable après réveil ({{count}} sessions audio vues). Essayez de jouer un son Windows (notification, ding) puis recliquez.",
      "unsupportedOs": "Mode spectacle non supporté sur cet OS."
    },
    "sleep": {
      "caffeinateFailed": "Impossible d'empêcher la mise en veille (caffeinate : {{detail}}). Désactivez la veille manuellement dans Réglages Système > Batterie.",
      "pipeMissing": "Impossible d'empêcher la mise en veille (tube absent).",
      "systemdInhibitMissing": "Impossible d'empêcher la mise en veille : systemd-inhibit est introuvable. Désactivez la veille manuellement.",
      "systemdInhibitNoLock": "Impossible d'empêcher la mise en veille : systemd-inhibit n'a pas pris le verrou. Désactivez la veille manuellement.",
      "systemdInhibitNoLockDetail": "Impossible d'empêcher la mise en veille : systemd-inhibit n'a pas pris le verrou ({{detail}}). Désactivez la veille manuellement.",
      "threadInterrupted": "Impossible d'empêcher la mise en veille (thread interrompu).",
      "unsupportedOs": "Blocage de la mise en veille non supporté sur cet OS.",
      "windowsFailed": "Impossible d'empêcher la mise en veille (SetThreadExecutionState a échoué)."
    },
    "unknown": "Une erreur inconnue est survenue."
  },
  "home": {
    "act": {
      "create": "Nouveau numéro",
      "open": "Ouvrir un numéro",
      "recents": "Numéros récents",
      "sectionTitle": "Numéro"
    },
    "createAct": {
      "folderLabel": "Dossier du numéro",
      "nameLabel": "Nom du numéro",
      "namePlaceholder": "Ex : Tango de la rose",
      "nameRequired": "Veuillez saisir un nom de numéro.",
      "title": "Nouveau numéro"
    },
    "createShow": {
      "folderLabel": "Dossier du projet",
      "nameLabel": "Nom du spectacle",
      "namePlaceholder": "Ex : Cabaret de printemps 2025",
      "nameRequired": "Veuillez saisir un nom de spectacle.",
      "title": "Nouveau spectacle"
    },
    "errors": {
      "actNotFound": "Numéro introuvable : \"{{name}}\". Il a peut-être été déplacé ou supprimé.",
      "folderPicker": "Impossible d'ouvrir le sélecteur : {{detail}}",
      "import": "Impossible d'importer : {{detail}}",
      "openAct": "Impossible d'ouvrir ce numéro : {{detail}}",
      "openProject": "Impossible d'ouvrir ce projet : {{detail}}",
      "projectNotFound": "Projet introuvable : \"{{name}}\". Il a peut-être été déplacé ou supprimé."
    },
    "folderPlaceholder": "Chemin du dossier...",
    "folderRequired": "Veuillez choisir un dossier.",
    "folderWillBeCreated": "Le dossier sera créé s'il n'existe pas.",
    "removeFromList": "Retirer de la liste",
    "show": {
      "create": "Nouveau spectacle",
      "open": "Ouvrir un spectacle",
      "recents": "Spectacles récents",
      "sectionTitle": "Spectacle"
    },
    "tagline": "Gestion audio pour spectacles cabaret"
  },
  "parts": {
    "act": {
      "hint": "Un passage avec ses musiques et ses pauses.",
      "label": "Numéro"
    },
    "changeType": "Changer le type",
    "duration": {
      "atLeast": "≥ {{duration}}",
      "atLeastTitle": "Durée minimale : les pauses sans durée et les pistes pas encore mesurées ne sont pas comptées",
      "title": "Durée de lecture de cette partie"
    },
    "emptyAct": "Aucun élément — ajoutez une musique ou une pause.",
    "hostSegment": {
      "hint": "Un moment d'annonce ou de transition.",
      "label": "Présentation"
    },
    "importAct": {
      "hint": "Depuis un fichier .regiesonnumero exporté.",
      "label": "Importer un numéro"
    },
    "importCloud": {
      "hint": "Récupérer un numéro partagé via son code.",
      "label": "Importer depuis le cloud"
    },
    "intermission": {
      "hint": "Une pause entre deux moments du spectacle.",
      "label": "Entracte"
    }
  },
  "preflight": {
    "allGood": "Tout est bon, aucune anomalie détectée.",
    "audioDeviceMissing": "Sortie audio sélectionnée introuvable. Vérifiez vos périphériques dans les paramètres.",
    "batteryLowNoEstimate": "Batterie à {{percent}} %, et le système n'estime pas l'autonomie restante. Branchez l'ordinateur sur le secteur.",
    "batteryShorterThanAct": "Autonomie restante {{left}}, inférieure à la durée du numéro ({{total}}). Branchez l'ordinateur sur le secteur.",
    "batteryShorterThanActAtLeast": "Autonomie restante {{left}}, inférieure à la durée du numéro (au moins {{total}}). Branchez l'ordinateur sur le secteur.",
    "batteryShorterThanShow": "Autonomie restante {{left}}, inférieure à la durée du spectacle ({{total}}). Branchez l'ordinateur sur le secteur.",
    "batteryShorterThanShowAtLeast": "Autonomie restante {{left}}, inférieure à la durée du spectacle (au moins {{total}}). Branchez l'ordinateur sur le secteur.",
    "outputRoutingUnsupported": "Le choix de la sortie audio n'est pas pris en charge sur ce système : le son partira sur la sortie par défaut.",
    "title": "Vérification du spectacle",
    "trackEndBeyondFile": "Fin au-delà de la fin du fichier sur {{label}} : la piste sera jouée jusqu'au bout",
    "trackFadesTooLong": "Fade in + fade out plus long que la durée de lecture sur {{label}}",
    "trackFileMissing": "Fichier manquant sur {{label}}",
    "trackStartAfterEnd": "Début ≥ fin sur {{label}}",
    "trackStartBeyondFile": "Début au-delà de la fin du fichier sur {{label}} : rien ne sera joué",
    "trackVolumeZero": "Volume à 0 sur {{label}}"
  },
  "settings": {
    "audioOutput": {
      "loading": "Chargement des périphériques…",
      "missingDevice": "Périphérique introuvable (débranché ?)",
      "previewHint": "Utilisée pour écouter une piste dans ses réglages, par exemple un casque, pour que la pré-écoute ne parte jamais dans la sono.",
      "previewTitle": "Sortie de pré-écoute",
      "refresh": "Actualiser la liste",
      "systemDefault": "Défaut du système",
      "title": "Sortie audio",
      "unnamedDevice": "Périphérique audio"
    },
    "keyBindings": {
      "disable": "Désactiver le raccourci",
      "forbiddenKey": "La touche « {{key}} » ne peut pas être utilisée.",
      "keys": {
        "backspace": "Retour",
        "delete": "Suppr",
        "escape": "Échap",
        "space": "Espace"
      },
      "next": "Piste suivante",
      "none": "Aucune touche",
      "panicFade": "Fondu d'urgence (2 s) puis arrêt",
      "playPause": "Lecture / Pause",
      "pressAKey": "Appuyez sur une touche…",
      "previous": "Élément précédent / retour au début de la piste",
      "reset": "Réinitialiser au défaut",
      "seekBackward": "Reculer de 5 s",
      "seekForward": "Avancer de 5 s",
      "stop": "Stop",
      "title": "Commandes"
    },
    "language": {
      "systemDefault": "Langue du système",
      "title": "Langue"
    },
    "playback": {
      "crossfade": "Fondu enchaîné entre deux pistes (secondes)",
      "crossfadeHint": "0 pour désactiver. La piste suivante démarre pendant que la précédente s'éteint ; une pause garde son silence.",
      "protectStop": "Protéger Stop : appuyer deux fois pour arrêter",
      "protectStopHint": "Évite qu'un appui réflexe sur la touche Stop coupe le spectacle. Le fondu d'urgence reste disponible en un seul appui.",
      "title": "Lecture"
    },
    "updates": {
      "blockedDuringShow": "Installation impossible pendant le mode spectacle ou une lecture.",
      "check": "Chercher les mises à jour",
      "checkError": "Erreur de vérification",
      "checking": "Vérification…",
      "install": "Installer v{{version}}",
      "installing": "Installation…",
      "title": "Mises à jour",
      "upToDate": "À jour"
    },
    "ytDlp": {
      "autoUpdate": "Mettre à jour automatiquement au démarrage",
      "title": "yt-dlp (téléchargement YouTube)",
      "unknownVersion": "Version inconnue",
      "update": "Mettre à jour",
      "updating": "Mise à jour…",
      "version": "Version {{version}}"
    }
  },
  "share": {
    "cloudShare": {
      "backgroundHint": "Vous pouvez fermer cette fenêtre : l'envoi continue, et vous serez prévenu à la fin.",
      "caption": "Communiquez ce code pour que votre destinataire récupère l'archive :",
      "clickToCopy": "Cliquer pour copier",
      "copy": "Copier",
      "copyFailed": "Copie impossible. Sélectionnez le code pour le copier à la main.",
      "expiry": "Hébergé sur Litterbox — le fichier expire automatiquement au bout de 72 heures.",
      "failedToast": "Échec du partage : {{detail}}",
      "readyToast": "Partage terminé. Code : {{code}}",
      "showCode": "Voir le code",
      "title": "Partage cloud",
      "unknownError": "Erreur inconnue",
      "uploading": "Téléversement en cours…"
    },
    "export": {
      "actTitle": "Exporter le numéro",
      "cloud": "Partager sur le cloud",
      "cloudHint": "Téléverser l'archive et obtenir un code à transmettre.",
      "file": "Exporter en fichier {{ext}}",
      "fileHint": "Enregistrer une archive sur le disque pour la partager manuellement.",
      "showTitle": "Exporter le spectacle"
    },
    "import": {
      "actTitle": "Récupérer un numéro",
      "codeLabel": "Code de partage",
      "codePlaceholder": "Ex : AbCdEf12",
      "codeRequired": "Veuillez saisir un code.",
      "inProgress": "Téléchargement et extraction en cours…",
      "showTitle": "Récupérer un spectacle",
      "submit": "Récupérer"
    },
    "open": {
      "actTitle": "Ouvrir un numéro",
      "cloud": "Sur le cloud",
      "cloudHint": "Saisir un code pour récupérer une archive partagée en ligne.",
      "file": "Un fichier {{ext}}",
      "fileHint": "Décompresser une archive {{ext}} dans un dossier du disque.",
      "folder": "Un dossier sur l'ordinateur",
      "folderActHint": "Choisir le dossier d'un numéro existant.",
      "folderShowHint": "Choisir le dossier d'un spectacle existant.",
      "showTitle": "Ouvrir un spectacle"
    }
  },
  "updater": {
    "available": "Mise à jour disponible — version {{version}}",
    "confirmInstall": "Installer et redémarrer",
    "confirmMessage": "Régie Son va se fermer pour installer la version {{version}}, puis redémarrer.",
    "confirmTitle": "Installer la mise à jour ?",
    "dismiss": "Ignorer",
    "install": "Installer",
    "installing": "Installation…",
    "installingPercent": "Installation {{percent}}%"
  }
}
